### ISSUE TITLE
Handle if sha256 is not installed in `./test.sh`

### ISSUE THREAD

**Issue by lauraGgit** [HHS/TANF-app#6]
In building the docker for the first time I got:
```
./test.sh: line 9: sha256sum: command not found
./test.sh: line 10: sha256sum: command not found
```

We should account for this in the script.

FYI - looks like the whole build will fail without this.

**Comment by timothy-spencer** [comment]
It will fail if you are doing it locally.  It doesn't fail if you are running it in docker or circle.

But https://github.com/HHS/TANF-app/pull/7 should fix this!

**Comment by lauraGgit** [comment]
Hmm -- I was running what looked to be the docker startup instructions.

**Comment by timothy-spencer** [comment]
Right, if test.sh is run inside of docker (like it is in circleci), then it works because linux has sha256sum installed.  But if you run ./test.sh on your mac, it will not unless you have done a `brew install sha256sum` or whatever.
